export const JOB_LOAD_REQ = "JOB_LOAD_REQ";
export const JOB_LOAD_SUCC = "JOB_LOAD_SUCC";
export const JOB_LOAD_FAIL = "JOB_LOAD_FAIL";
export const JOB_LOAD_RESET = "JOB_LOAD_RESET";

export const JOB_LOAD_SINGLE_REQ = "JOB_LOAD_SINGLE_REQ";
export const JOB_LOAD_SINGLE_SUCC = "JOB_LOAD_SINGLE_SUCC";
export const JOB_LOAD_SINGLE_FAIL = "JOB_LOAD_SINGLE_FAIL";
export const JOB_LOAD_SINGLE_RESET = "JOB_LOAD_SINGLE_RESET";

export const REGISTER_JOB_REQ = "REGISTER_JOB_REQ";
export const REGISTER_JOB_SUCC = "REGISTER_JOB_SUCC";
export const REGISTER_JOB_FAIL = "REGISTER_JOB_FAIL";
export const REGISTER_JOB_RESET = "REGISTER_JOB_RESET";

export const DELETE_JOB_REQ = "DELETE_JOB_REQ";
export const DELETE_JOB_SUCC = "DELETE_JOB_SUCC";
export const DELETE_JOB_FAIL = "DELETE_JOB_FAIL";
export const DELETE_JOB_RESET = "DELETE_JOB_RESET";


export const EDIT_JOB_REQ = "EDIT_JOB_REQ";
export const EDIT_JOB_SUCC = "EDIT_JOB_SUCC";
export const EDIT_JOB_FAIL = "EDIT_JOB_FAIL";
export const EDIT_JOB_RESET = "EDIT_JOB_RESET";