export const JOB_TYPE_LOAD_REQ = "JOB_TYPE_LOAD_REQ";
export const JOB_TYPE_LOAD_SUCC = "JOB_TYPE_LOAD_SUCC";
export const JOB_TYPE_LOAD_FAIL = "JOB_TYPE_LOAD_FAIL";
export const JOB_TYPE_LOAD_RESET = "JOB_TYPE_LOAD_RESET";

export const CREATE_JOB_TYPE_REQ = "CREATE_JOB_TYPE_REQ";
export const CREATE_JOB_TYPE_SUCC = "CREATE_JOB_TYPE_SUCC";
export const CREATE_JOB_TYPE_FAIL = "CREATE_JOB_TYPE_FAIL";
export const CREATE_JOB_TYPE_RESET = "CREATE_JOB_TYPE_RESET";
