export const USER_SIGNIN_REQ = "USER_SIGNIN_REQ";
export const USER_SIGNIN_SUCC = "USER_SIGNIN_SUCC";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNIN_RESET = "USER_SIGNIN_RESET";

export const USER_SIGNUP_REQ = "USER_SIGNUP_REQ";
export const USER_SIGNUP_SUCC = "USER_SIGNUP_SUCC";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";
export const USER_SIGNUP_RESET = "USER_SIGNUP_RESET";

export const USER_LOGOUT_REQ = "USER_LOGOUT_REQ";
export const USER_LOGOUT_SUCC = "USER_LOGOUT_SUCC";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";
export const USER_LOGOUT_RESET = "USER_LOGOUT_RESET";

export const USER_LOAD_REQ = "USER_LOAD_REQ";
export const USER_LOAD_SUCC = "USER_LOAD_SUCC";
export const USER_LOAD_FAIL = "USER_LOAD_FAIL";
export const USER_LOAD_RESET = "USER_LOAD_RESET";

export const USER_APPLY_JOB_REQ = "USER_APPLY_JOB_REQ";
export const USER_APPLY_JOB_SUCC = "USER_APPLY_JOB_SUCC";
export const USER_APPLY_JOB_FAIL = "USER_APPLY_JOB_FAIL";
export const USER_APPLY_JOB_RESET = "USER_APPLY_JOB_RESET";

export const ALL_USER_LOAD_REQ = "ALL_USER_LOAD_REQ";
export const ALL_USER_LOAD_SUCC = "ALL_USER_LOAD_SUCC";
export const ALL_USER_LOAD_FAIL = "ALL_USER_LOAD_FAIL";
export const ALL_USER_LOAD_RESET = "ALL_USER_LOAD_RESET";